version: '3.3'
services:

  hewalex2mqtt:
    image: chibald/hewalex2mqtt:latest
    network_mode: host
    environment:
      MQTT_ip: 192.168.1.2
      MQTT_port: 1883
      MQTT_authentication: 'False'
      MQTT_user: ''
      MQTT_pass: ''
      Device_Zps_Enabled: 'True'
      Device_Zps_Address: '192.168.1.7'
      Device_Zps_Port: 8899
      Device_Zps_MqttTopic: 'SolarBoiler'
      Device_Pcwu_Enabled: 'True'
      Device_Pcwu_Address: '192.168.1.8'
      Device_Pcwu_Port: '8899'
      Device_Pcwu_MqttTopic: 'Heatpump'
